name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name : Docker Login
      run: docker login -u ${{secrets.dockeruser}} -p ${{secrets.dockerpass}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.dockeruser}}/tesapakek
    - name: Docker Push
      run: docker push ${{secrets.dockeruser}}/tesapakek
